/*
 * TransformIT 8.0 (GA) EvalKit
 *
 * Copyright (C) Arxan Technologies Inc. 2017.
 * All rights Reserved.
 *
 *
 * Portions of the information disclosed herein are protected by
 * U.S. Patent No. 6,941,463, U.S. Patent No. 6,957,341, U.S. Patent 7,287,166,
 * U.S. Patent 7,707,433, U.S. Patent 7,757,097, U.S. Patent 7,853,018,
 * U.S. Patent 8,510,571, U.S. Patent 9,262,600, and Patents Pending.
 *
 */

#ifndef __MONT_BIGINT_DEFS_H__
#define __MONT_BIGINT_DEFS_H__

#ifdef __cplusplus
extern "C" {
#endif



#define MONTBI_WO_MASK  0x00000001
#define MONTBI_WO_LEW   0x00000000
#define MONTBI_WO_BEW   0x00000001

#define MONTBI_BO_MASK  0x00000006
#define MONTBI_BO_LEB   0x00000002
#define MONTBI_BO_BEB   0x00000004
#define MONTBI_BO_HB    0x00000000

#define MONTBI_SIZE_MASK 0x00000018
#define MONTBI_SIZE_8    0x00000000
#define MONTBI_SIZE_16   0x00000008
#define MONTBI_SIZE_32   0x00000010
#define MONTBI_SIZE_64   0x00000018

#define MONTBI_FORMAT_BEWLEB32 (MONTBI_WO_BEW | MONTBI_BO_LEB | MONTBI_SIZE_32)
#define MONTBI_FORMAT_BEWLEB64 (MONTBI_WO_BEW | MONTBI_BO_LEB | MONTBI_SIZE_64)
#define MONTBI_FORMAT_BEWBEB8  (MONTBI_WO_BEW | MONTBI_BO_BEB | MONTBI_SIZE_8)
#define MONTBI_FORMAT_BEWBEB16 (MONTBI_WO_BEW | MONTBI_BO_BEB | MONTBI_SIZE_16)
#define MONTBI_FORMAT_BEWBEB32 (MONTBI_WO_BEW | MONTBI_BO_BEB | MONTBI_SIZE_32)
#define MONTBI_FORMAT_BEWBEB64 (MONTBI_WO_BEW | MONTBI_BO_BEB | MONTBI_SIZE_64)
#define MONTBI_FORMAT_LEWLEB8  (MONTBI_WO_LEW | MONTBI_BO_LEB | MONTBI_SIZE_8)
#define MONTBI_FORMAT_LEWLEB16 (MONTBI_WO_LEW | MONTBI_BO_LEB | MONTBI_SIZE_16)
#define MONTBI_FORMAT_LEWLEB32 (MONTBI_WO_LEW | MONTBI_BO_LEB | MONTBI_SIZE_32)
#define MONTBI_FORMAT_LEWLEB64 (MONTBI_WO_LEW | MONTBI_BO_LEB | MONTBI_SIZE_64)
#define MONTBI_FORMAT_LEWBEB32 (MONTBI_WO_LEW | MONTBI_BO_BEB | MONTBI_SIZE_32)
#define MONTBI_FORMAT_LEWBEB64 (MONTBI_WO_LEW | MONTBI_BO_BEB | MONTBI_SIZE_64)
#define MONTBI_FORMAT_LEWHB32  (MONTBI_WO_LEW | MONTBI_BO_HB  | MONTBI_SIZE_32)
#define MONTBI_FORMAT_LEWHB64  (MONTBI_WO_LEW | MONTBI_BO_HB  | MONTBI_SIZE_64)
#define MONTBI_FORMAT_BEWHB32  (MONTBI_WO_BEW | MONTBI_BO_HB  | MONTBI_SIZE_32)
#define MONTBI_FORMAT_BEWHB64  (MONTBI_WO_BEW | MONTBI_BO_HB  | MONTBI_SIZE_64)



#define MONTBI_OK                   0
#define MONTBI_INPUT_TOO_LARGE      1
#define MONTBI_OUTPUT_TOO_LARGE     2
#define MONTBI_UNSUPP_FORMAT        3
#define MONTBI_UNSUPP_ARCH          4
#define MONTBI_INTERNAL_ERROR       5
#define MONTBI_NULL_ARG             6
#define MONTBI_INPUT_TOO_LARGE_MOD  7
#define MONTBI_NO_MEMORY            8


#ifdef __cplusplus
}
#endif

#endif 

